### ISSUE TITLE
Désactivation de l'echo du clavier

### ISSUE THREAD

**Issue by DJTgeekk** [eserandour/Minitel1B_Hard#6]
Par défaut le minitel est dans un mode ou il recopie les entrées clavier directement à l'écran. Cela peut être désactivé avec `Fnct + T puis E`
Il serai intéressant de pouvoir faire cela sans interactions de l'utilisateur. Cela semble possible à l'aide de commandes PROG et des codes dans l'image extraite de la doc si dessous.

![Captureeee](https://user-images.githubusercontent.com/86717785/153511688-f09b3319-4a88-43cb-b635-142c5fa410c0.PNG)

Ces codes n'étant pas dans la liste des #define dans le fichier .h je suppose que cette fonctionnalité n'a pas été implémentée

**Comment by eserandour** [comment]
Voir : byte echo(boolean commande);  // Active ou désactive l'écho à l'écran de ce qui est tapé au clavier
